INSERT ALL
	INTO IngredientInteraction (InteractionNo, InteractionIngredient1, InteractionIngredient2, InteractionDetail, InteractionDosage)
	VALUES('1', '6', '5', '고용량의 비타민 C를 비타민 B12와 함께 복용하면, 비타민 B12가 체내에서 분해되어 효능이 떨어질 수 있습니다. 비타민 B12는 신경 건강과 적혈구 생성에 중요한 역할을 합니다.', '비타민 C와 비타민 B12를 다른 시간대에 복용하는 것이 좋습니다.')
	INTO IngredientInteraction (InteractionNo, InteractionIngredient1, InteractionIngredient2, InteractionDetail, InteractionDosage)
	VALUES('2', '6', '9', '비타민 C는 철분의 흡수를 촉진합니다. 이는 철분이 부족한 사람들에게는 긍정적일 수 있지만, 과도한 철분 축적이 위험한 사람들에게는 문제가 될 수 있습니다.', '철분 보충제와 비타민 C를 함께 복용할 때는 철분 수치를 모니터링해야 하며, 필요에 따라 복용 간격을 두는 것이 좋습니다.')
	INTO IngredientInteraction (InteractionNo, InteractionIngredient1, InteractionIngredient2, InteractionDetail, InteractionDosage)
	VALUES ('3', '5', '8', '칼슘은 비타민 B12의 흡수를 저해할 수 있습니다. 특히 나이가 들수록 칼슘과 B12 간의 상호작용이 더 두드러질 수 있습니다.', '칼슘과 비타민 B12는 다른 시간대에 복용하는 것이 좋습니다.')
	INTO IngredientInteraction (InteractionNo, InteractionIngredient1, InteractionIngredient2, InteractionDetail, InteractionDosage)
	VALUES ('4', '7', '10', '비타민 D3는 마그네슘을 활성화시켜 뼈 건강에 중요한 역할을 하지만, 과도한 비타민 D 복용은 체내 마그네슘을 고갈시킬 수 있습니다. 마그네슘 결핍은 피로, 근육 경련을 유발할 수 있습니다.', '비타민 D3를 복용할 때는 마그네슘이 포함된 종합비타민을 함께 복용하거나, 마그네슘 보충제를 복용하는 것이 좋습니다.')
	INTO IngredientInteraction (InteractionNo, InteractionIngredient1, InteractionIngredient2, InteractionDetail, InteractionDosage)
	VALUES ('5', '4', '9', '종합비타민에는 다양한 비타민과 미네랄이 포함되어 있지만, 철분과 칼슘이 함께 들어 있을 경우 서로 흡수를 방해할 수 있습니다.', '철분과 칼슘을 함께 복용하지 않는 것이 좋으며, 종합비타민에 들어 있는 철분과 칼슘이 적절히 흡수되도록 다른 시간대에 복용해야 합니다.')
	INTO IngredientInteraction (InteractionNo, InteractionIngredient1, InteractionIngredient2, InteractionDetail, InteractionDosage)
	VALUES ('6', '4', '8', '종합비타민에는 다양한 비타민과 미네랄이 포함되어 있지만, 철분과 칼슘이 함께 들어 있을 경우 서로 흡수를 방해할 수 있습니다.', '철분과 칼슘을 함께 복용하지 않는 것이 좋으며, 종합비타민에 들어 있는 철분과 칼슘이 적절히 흡수되도록 다른 시간대에 복용해야 합니다.')
	INTO IngredientInteraction (InteractionNo, InteractionIngredient1, InteractionIngredient2, InteractionDetail, InteractionDosage)
	VALUES ('7', '10', '9', '마그네슘을 복용 시 위의 산도가 낮아지면, 철분에 포함된 영양분 흡수가 저하될 수 있습니다. 특히, 산화마그네슘 성분은 위에서 산도를 감소시키는 역할을 하기 때문에 철분이 혈류에 제대로 흡수되지 않아 철분의 효과가 떨어질 수 있습니다.', '마그네슘과 철분을 모두 복용해야 하는 경우, 상호작용을 최소화하기 위해 2시간 이상 간격을 두고 복용하는 것이 좋습니다. 비타민이나 허브 등 다른 영양제 복용 시에도 상호작용 가능성을 줄이기 위해, 복용 중인 모든 약물에 대해 의사나 약사에게 알리는 것을 권장드립니다.')
	INTO IngredientInteraction (InteractionNo, InteractionIngredient1, InteractionIngredient2, InteractionDetail, InteractionDosage)
	VALUES ('8', '9', '8', '칼슘 복용 시, 칼슘에 포함된 탄산 칼슘 성분이 위산을 중화시키는 역할을 하여 철분이 혈류로 흡수되는 것을 방해할 수 있습니다.', '칼슘과 철분을 모두 복용해야 하는 경우, 칼슘 복용 전 최소 2시간 또는 복용 2시간 후에 철분을 복용하는 것이 좋습니다. 이를 통해 칼슘으로 인한 위산 저하가 철분 흡수에 미치는 영향을 최소화할 수 있습니다. 추가적인 사항은 반드시 의사와 상의한 후에 결정하는 것을 권장드립니다.')
	INTO IngredientInteraction (InteractionNo, InteractionIngredient1, InteractionIngredient2, InteractionDetail, InteractionDosage)
	VALUES ('9', '9', '11', '황산 아연과 철분을 함께 경구로 투여할 경우, 두 성분이 서로의 흡수를 감소시킬 수 있습니다. 임상 연구에 따르면 철분과 아연을 동시에 보충했을 때 영양실조 영아의 성장 및 철분과 아연 상태가 각각 하나만 보충했을 때보다 개선 효과가 감소한 것으로 나타났습니다.', '영양실조 환자의 경우, 철분과 아연을 동시에 복용할 때 치료 효과 감소를 모니터링하는 것이 좋습니다. 또한, 연구에 따르면 두 성분의 복용 시간을 12시간 간격으로 나누면 상호작용의 영향을 줄일 수 있습니다.')
	INTO IngredientInteraction (InteractionNo, InteractionIngredient1, InteractionIngredient2, InteractionDetail, InteractionDosage)
	VALUES ('10', '15', '6', '밀크씨슬과 함께 복용할 경우, 체내의 활성산소를 너무 많이 제거하여 항산화 효과가 과도해질 수 있습니다.', '비타민 C와 밀크시슬을 함께 복용할 때는 복용 간격을 두는 것이 좋습니다.')
	INTO IngredientInteraction (InteractionNo, InteractionIngredient1, InteractionIngredient2, InteractionDetail, InteractionDosage)
	VALUES ('11', '2', '8', '소화불량을 일으킬 수 있습니다.', '루테인과 칼슘의 복용 간격을 6시간 이상 두는 것을 권장합니다.')
	INTO IngredientInteraction (InteractionNo, InteractionIngredient1, InteractionIngredient2, InteractionDetail, InteractionDosage)
	VALUES ('12', '2', '10', '소화불량을 일으킬 수 있습니다.', '루테인과 마그네슘의 복용 간격을 6시간 이상 두는 것을 권장합니다.')
	INTO IngredientInteraction (InteractionNo, InteractionIngredient1, InteractionIngredient2, InteractionDetail, InteractionDosage)
	VALUES ('13', '13', '6', '산성이 강한 비타민 C는 유산균의 생존율을 떨어뜨리기 때문에 같이 먹는 것은 좋지 않습니다.', '유산균은 장 건강을 위해 빈속에 먹어야 하고, 비타민 C는 반대로 빈속에 먹으면 속이 쓰리기 때문에 두 영양제는 함께 복용하지 않는 것이 좋습니다.')

	SELECT 1 FROM DUAL; 

