CREATE TABLE wishList (
    WishID NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOT NULL, 
    UserID VARCHAR2(50) NOT NULL,  
    SupID NUMBER NOT NULL,         
    PRIMARY KEY(WishID),
    FOREIGN KEY (UserID) REFERENCES users(UserID), 
    FOREIGN KEY (SupID) REFERENCES supplement(SupID) 
);