CREATE TABLE supplement (
    SupID NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000), 
    SupName VARCHAR2(512) NOT NULL,               
    SupPrice NUMBER NOT NULL,                     
    SupBrand VARCHAR2(150) NOT NULL,             
    SupDosage VARCHAR2(2000) NOT NULL, 
    SupNutri VARCHAR2(3000) NOT NULL,               
    SupNutriInfo VARCHAR2(1000) NOT NULL,                 
    SupPrecautions VARCHAR2(3000) NOT NULL,                 
    SupDetail VARCHAR2(3500) NOT NULL,                     
    SupImg BLOB,                                   
    PRIMARY KEY (SupID)                            
);